TypeScript migration
PretendoNetwork/account pull request #65
Opened 2023-03-03 17:40 UTC by jonbarrow

Creating as a draft PR because a lot more work and testing needs to be done to ensure everything still works. This is the first step towards moving the account server to TypeScript

2023-03-04 20:58 UTC, jonbarrow commented
I believe I have checked all major functionality and confirmed it is working. There is still more which needs to be done, however, with regards to getting the type system up to par. At the moment there is very little typing being done, and it's an akward mix of typed and un-typed data

2023-03-07 02:22 UTC, jonbarrow commented
@mrjvs @Pandawan if you wouldn't mind giving this a look-over when you have time please

2023-03-07 17:28 UTC, mrjvs requested changes
I skipped most the actual logic, I only really looked at the use of typescript. (as that is what is being changed in the PR)

2023-03-07 22:45 UTC, jonbarrow commented on src/cache.ts
> +};
This was largely leftover from the require->import part of the migration, and I found that replacing `module.exports` with `export default` resulted in less broken imports at the time. I agree this is messy though, thank you for catching this!

2023-03-07 22:47 UTC, jonbarrow commented on src/database.ts
> +	}
Left over from before TS, good catch!

2023-03-07 22:49 UTC, jonbarrow commented on src/database.ts
> +		'email.address': new RegExp(email, 'i') // * Ignore case
I'm confused as to why this is more unsafe than storing the email twice? Storing the email in lowercase and then converting the input to lowercase here would achive the same result as just ignoring the case on the query, no? And if it's not a valid email address it should just not return a document, which is expected, is it not?

2023-03-07 22:50 UTC, jonbarrow commented on src/database.ts
> +	const parts: string[] = decoded.split(' ');
Putting this here as well for completeness sake even though we discussed this on Discord: After discussing this further this is really a matter of opinion/preference and mine is to fully use the type system

2023-03-07 23:00 UTC, jonbarrow commented on src/database.ts
> +	return <PNIDProfile>{
Is this cast unneccesary when viewed from the eyes of "let TS infer the type"? If so, does this comment still apply now that you know I prefer to strictly type everything?

2023-03-08 00:05 UTC, mrjvs commented on src/database.ts
> +	return <PNIDProfile>{
yes it does still apply, cuz casting is fundementally lying to typescript, you're telling the compiler that yes, this is actually this type that im telling it to be, even if its not. so you could be returning data thats missing a bunch of fields and typescript would not complain.

for example, with this cast, typescript will not complain at all even tho its completely wrong:
<img src="https://i.imgur.com/g6A8pOi.png" />

but with strictly annotated types, ts does complain:
<img src="https://i.imgur.com/fi8TOzw.png" />

2023-03-08 00:16 UTC, mrjvs commented on src/database.ts
> +		'email.address': new RegExp(email, 'i') // * Ignore case
ill dm you about it

2023-03-19 20:35 UTC, jonbarrow commented
@mrjvs I believe I have resolved all issues, look good?

2023-04-27 19:35 UTC, merged