support: implement send_confirmation/pin/:email
PretendoNetwork/account pull request #99
Opened 2024-06-29 20:34 UTC by ItzSwirlz

Resolves #96 

### Changes:

- Implements the `send_confirmation/pin/:email` route. Same method as `resend_confirmation` but gets the PNID from the database via email address instead off PID.

- [X] I have read and agreed to the [Code of Conduct](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have read and complied with the [contributing guidelines](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CONTRIBUTING.md).
- [X] What I'm implementing was an [approved issue](../issues?q=is%3Aopen+is%3Aissue+label%3Aapproved).
- [ ] I have tested all of my changes.

2024-06-29 22:28 UTC, jonbarrow requested changes
Other than this, looks good to me :+:

2024-06-29 22:28 UTC, jonbarrow commented on src/services/nnas/routes/support.ts
> +	const email = String(request.params.email)
`String` here is redundant, since it's already a string. Also missing a semicolon

2024-06-30 09:27 UTC, DaniElectra commented
This is not accurate to what the real endpoint does, this endpoint is used to send a "confirmation" email that the email has been registered on Parental Controls (see https://github.com/PretendoNetwork/account/issues/27). It would make more sense to use `sendEmailConfirmedEmail()`, *if anything*.

2024-06-30 15:39 UTC, ItzSwirlz commented
> This is not accurate to what the real endpoint does, this endpoint is used to send a "confirmation" email that the email has been registered on Parental Controls (see #27). It would make more sense to use `sendEmailConfirmedEmail()`, _if anything_.

Should I make a new function `sendParentalControlsConfirmedEmail()` for this purpose?

2024-07-03 01:49 UTC, ItzSwirlz commented
![image](https://github.com/PretendoNetwork/account/assets/24401303/7d90167a-d98c-4690-97f3-c0d54e8c0a54)

It works. 102-2534 is no longer shown when changing email address.

2025-02-01 20:10 UTC, merged